version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cn-django-test

hooks:
  ApplicationStop:
    - location: ./stop_docker.sh
      timeout: 300
      runas: root

  BeforeInstall: 
    - location: ./pre_install.sh
      timeout: 300
      runas: root

  Install: []        # Explicitly leave this empty
  AfterInstall: []   # Explicitly leave this empty

  ApplicationStart:
    - location: ./start_docker.sh
      timeout: 300
      runas: root

  ValidateService: []  # Explicitly leave this empty
