version: 0.0
os: linux
files:
  - source: /home/ec2-user/cn-django-test
    destination: /home/ec2-user/cn-django-test

hooks:
  BeforeInstall: []

  Install: []        # Explicitly leave this empty
  AfterInstall: []   # Explicitly leave this empty

  ApplicationStart:
    - location: ./start_docker.sh
      timeout: 300
      runas: root
  ValidateService: []  # Explicitly leave this empty
  

  ApplicationStop:
    - location: ././stop_docker.sh.sh
      timeout: 300
      runas: root


