version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cn-django-test

hooks:
  ApplicationStop:
    - location: ./stop_docker.sh
      timeout: 300
      runas: root

  Install: []        # Leave empty if not needed
  AfterInstall: []   # Leave empty if not needed

  ApplicationStart:
    - location: ./start_docker.sh
      timeout: 300
      runas: root

  ValidateService: []  # Leave empty if not needed
