version: 0.0
os: linux
files:
  - source: .
    destination: /app/

hooks:
  BeforeInstall: 
    - location: ./pre_install.sh
      timeout: 300
      runas: root
      
  Install: []       
  AfterInstall: []   

  ApplicationStart:
    - location: ./start_docker.sh
      timeout: 300
      runas: root
  ValidateService: []  # Explicitly leave this empty
  

  ApplicationStop:
    - location: ./stop_docker.sh
      timeout: 300
      runas: root


